### ISSUE TITLE
Find location for focus group

### ISSUE THREAD

**Issue by ghost** [EcoStarsClub/letsgo#1]
Should we do this in Monarchy? Or will that send a mixed signal to teachers being that it's a nightclub?

**Comment by ghost** [comment]
@shellyperlman Are we doing it in Monarchy then?

**Comment by shellyperlman** [comment]
did you read the email from the meeting with the teacher? 
She told us that a focus group is not going to be easy to do for teachers. She gave me a contact at the Science department of palm beach school district. she said we should get a meeting with him and show him everything and get his feedback - and when he is on board with us, he will give us contacts to other teachers, not to mention make sure we are on the right track..... he then shares the programs with all the schools in Palm Beach county!! :)
