### ISSUE TITLE
email for ima

### ISSUE THREAD

**Issue by shellyperlman** [EcoStarsClub/letsgo#13]
hi sar can you make livna@ecostarsclub.com
i have livna@ecostarsclub.org and i can forward it to her there.

**Comment by ghost** [comment]
@shellyperlman she has an email already livna@ecostars.club, can you forward the .org to that one?

**Comment by ghost** [comment]
@shellyperlman @Ecolive I added emails for all of us at ecostarscluib.org, it's the same settings as the ecostarsclub.com but with .org at the end and a new password. @Ecolive let me know if you need help setting it up on your computer.
