### ISSUE TITLE
Decide on domain name

### ISSUE THREAD

**Issue by ghost** [EcoStarsClub/letsgo#2]
Should we go with ecostars.club or ecostarsclub.org?
@shellyperlman what do you think?

**Comment by shellyperlman** [comment]
www.ecostarsclub.org - if you give me details, I can call there and ask them to transfer the name to the non profit.

**Comment by shellyperlman** [comment]
hi chamyour, can you give me the details so that i can call and get .org transfered to us?

**Comment by ghost** [comment]
@shellyperlman just sent Randy this email:
Hi Randy!
Called GoDaddy finally and they said the last transfer expired because I didn't enter the auth codes for the transfer. They re-initiated it, and you should be getting 3 emails, 2 from GoDaddy and 1 from your registrar... could you please forward these to me and then I can get the transfer completed. Thanks!

**Comment by ghost** [comment]
10-6-2015

Sar,

I’ll look out for it. The email should go to ipadmin@hostleasing.net. I logged into the account and confirmed that there are no pending transfers and that the domain is unlocked.

Regards,

Randy

10-5-2015

Hi Randy!
I called GoDaddy and they said it sometimes takes up to 7 biz days to process.
But if you don't get the email from Wild West by Friday, we should call Wild West and see why the auth code hasn't been sent, or which email address they sent the code to.

Best,
Sar

**Comment by ghost** [comment]
@shellyperlman please talk to Randy see how you can help him to contact Wild West to get the Authorization Code from them

**Comment by ghost** [comment]
@shellyperlman @Ecolive  Transfer complete! Yeay! Going forward, our official website is ecostarsclub.org
![screen shot 2015-10-11 at 6 43 47 pm](https://cloud.githubusercontent.com/assets/14277703/10419521/1f62c7d0-7048-11e5-8302-e1e4fdcdb20b.png)
